-- Campaign dynamic datasets support
set check_function_bodies = off;

create table if not exists public.campaigns_custom_metrics (
  id bigint generated by default as identity primary key,
  usuario_id bigint not null references public.usuarios(id) on delete cascade,
  dataset text not null,
  metric text not null,
  numeric_value numeric,
  text_value text,
  json_value jsonb,
  updated_at timestamptz not null default timezone('utc', now()),
  constraint campaigns_custom_metrics_value_check
    check (
      numeric_value is not null
      or text_value is not null
      or json_value is not null
    )
);

create unique index if not exists campaigns_custom_metrics_usuario_dataset_metric_key
  on public.campaigns_custom_metrics (usuario_id, dataset, metric);

create index if not exists campaigns_custom_metrics_usuario_idx
  on public.campaigns_custom_metrics (usuario_id);

comment on table public.campaigns_custom_metrics is 'Stores per-usuario campaign metrics produced by external jobs to power declarative rules (replacement for CUSTOM_SQL).';
comment on column public.campaigns_custom_metrics.dataset is 'Dataset identifier consumed by METRIC_CONDITION rules via metrics.datasets.<dataset>.<metric>.';
comment on column public.campaigns_custom_metrics.metric is 'Metric name within the dataset.';
comment on column public.campaigns_custom_metrics.numeric_value is 'Numeric value for the metric (optional).';
comment on column public.campaigns_custom_metrics.text_value is 'Text value for the metric (optional).';
comment on column public.campaigns_custom_metrics.json_value is 'JSON payload for complex metrics (optional).';
