name: CI

on:
	pull_request:
		branches: [ main, develop ]
	push:
		branches: [ develop ]

permissions:
	contents: read
	pull-requests: read

jobs:
	build-and-lint:
		runs-on: ubuntu-latest
		# Dynamic environment name based on branch
		environment: ${{ github.ref == 'refs/heads/main' && 'production' || (github.ref == 'refs/heads/develop' && 'develop' || 'preview') }}
		steps:
			- name: Checkout
				uses: actions/checkout@v4

			- name: Setup Node
				uses: actions/setup-node@v4
				with:
					node-version: 18
					cache: npm

			- name: Install deps
				run: npm ci

			- name: Lint
				run: npm run lint --if-present

			- name: Type check
				run: npm run typecheck --if-present || echo "No typecheck script"

			- name: Build
				run: npm run build

	preview-comment:
		if: ${{ github.event_name == 'pull_request' }}
		needs: build-and-lint
		runs-on: ubuntu-latest
		steps:
			- name: Add Vercel Preview Hint
				uses: actions/github-script@v7
				with:
					script: |
						const pr = context.payload.pull_request;
						const body = 'Revisa el deployment Preview en Vercel antes de aprobar.';
						await github.rest.issues.createComment({
							owner: context.repo.owner,
							repo: context.repo.repo,
							issue_number: pr.number,
							body
						});
